services:
  backend_test:
    container_name: backend_test
    image: backend_test:1.0.0
    env_file:
      - path: backend/.env.test
    build:
      context: ./backend
    ports:
      - '8081:8081'
    depends_on:
      - db_test
      - migrate
  migrate:
    container_name: migrate
    image: migrate:1.0.0
    env_file:
      - path: backend/.env.test
    build:
      context: ./backend
      dockerfile: migrate.Dockerfile
    depends_on:
      - db_test
  db_test:
    container_name: db_test
    image: postgres:16.3-alpine
    env_file:
      - path: db.test.env
    ports:
      - 5433:5432